// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Click struct {
	ID        int32
	UrlID     int32
	ClickedAt sql.NullTime
	IpAddress string
	UserAgent string
}

type Url struct {
	ID          int32
	ShortCode   string
	OriginalUrl string
	CreatedAt   sql.NullTime
}
