// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createURL = `-- name: CreateURL :execresult
INSERT INTO urls (short_code, original_url) VALUES (?, ?)
`

type CreateURLParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
}

const getAnalyticsByCode = `-- name: GetAnalyticsByCode :many
SELECT c.clicked_at, c.ip_address, c.user_agent
FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.short_code = ?
ORDER BY c.clicked_at DESC
`

type GetAnalyticsByCodeRow struct {
	ClickedAt sql.NullTime
	IpAddress string
	UserAgent string
}

func (q *Queries) GetAnalyticsByCode(ctx context.Context, shortCode string) ([]GetAnalyticsByCodeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAnalyticsByCode, shortCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnalyticsByCodeRow
	for rows.Next() {
		var i GetAnalyticsByCodeRow
		if err := rows.Scan(&i.ClickedAt, &i.IpAddress, &i.UserAgent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT id, short_code, original_url, created_at FROM urls WHERE short_code = ? LIMIT 1
`

func (q *Queries) GetURLByCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const recordClick = `-- name: RecordClick :exec
INSERT INTO clicks (url_id, ip_address, user_agent) VALUES (?, ?, ?)
`

type RecordClickParams struct {
	UrlID     int32
	IpAddress string
	UserAgent string
}

func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) error {
	_, err := q.db.ExecContext(ctx, recordClick, arg.UrlID, arg.IpAddress, arg.UserAgent)
	return err
}
